// Generated by CoffeeScript 1.7.1
(function() {
  var Auth;

  angular.module('BookStore').service('Auth', Auth = (function() {
    Auth.$inject = ['$location', '$rootScope', '$cookieStore', '$http'];

    function Auth($location, $rootScope, $cookieStore, $http) {
      $rootScope.user = $cookieStore.get('user') || {};
      $cookieStore.remove('user');
      this.login = function(email, password, callback) {
        if (callback == null) {
          callback = angular.noop;
        }
        return $http.post('/api/login?hashed=true', {
          email: email,
          password: password
        }).then(function(resp) {
          var data;
          data = resp.data;
          $rootScope.user = data;
          return callback(null, data);
        }, function(err) {
          return callback(err);
        });
      };
      this.logout = function(callback) {
        if (callback == null) {
          callback = angular.noop;
        }
        return $http.post('/api/logout').then(function(resp) {
          $rootScope.user = {};
          return callback();
        });
      };
    }

    return Auth;

  })());

}).call(this);

//# sourceMappingURL=auth.map
