// Generated by CoffeeScript 1.7.1
(function() {
  var BookDetailCtrl;

  angular.module('BookStore').controller('BookDetailCtrl', BookDetailCtrl = (function() {
    BookDetailCtrl.$inject = ['$routeParams', 'Book', '$location'];

    function BookDetailCtrl($routeParams, Book, location) {
      var id;
      this.Book = Book;
      this.location = location;
      id = $routeParams.bookId;
      this.book = Book.get({
        id: id
      });
    }

    BookDetailCtrl.prototype.update = function() {
      return this.book.$update().then(function() {
        return alert('Updated');
      })["catch"](function(resp) {
        var errors;
        errors = resp.data;
        return console.warn(errors);
      });
    };

    BookDetailCtrl.prototype.remove = function() {
      if (confirm('Do you want to delete this book?\n\nTHIS CANNOT BE UNDONE')) {
        return this.book.$remove().then((function(_this) {
          return function() {
            return _this.location.path('/books');
          };
        })(this));
      }
    };

    return BookDetailCtrl;

  })());

}).call(this);
