// Generated by CoffeeScript 1.7.1
(function() {
  var BookIndexCtrl;

  angular.module('BookStore').controller('BookIndexCtrl', BookIndexCtrl = (function() {
    function BookIndexCtrl(Book, Pagination) {
      this.Book = Book;
      this.Pagination = Pagination;
      this.update({
        skip: 0,
        limit: 12
      });
    }

    BookIndexCtrl.prototype.update = function(_arg) {
      var limit, query, skip, sort, _ref;
      _ref = _arg != null ? _arg : {}, skip = _ref.skip, limit = _ref.limit;
      query = this.query || '';
      sort = this.sort || 'price';
      return this.books = this.Book.query({
        limit: limit || 12,
        skip: skip || 0,
        search: query.length ? query : void 0,
        sort: sort
      }, (function(_this) {
        return function(data, headers) {
          return data.$paging = _this.Pagination(data, headers);
        };
      })(this));
    };

    return BookIndexCtrl;

  })());

}).call(this);
