// Generated by CoffeeScript 1.7.1
(function() {
  var HomeCtrl;

  angular.module('BookStore').controller('HomeCtrl', HomeCtrl = (function() {
    function HomeCtrl() {
      this.message = 'hello';
    }

    return HomeCtrl;

  })());

}).call(this);
