// Generated by CoffeeScript 1.7.1
(function() {
  var LoginCtrl;

  angular.module('BookStore').controller('LoginCtrl', LoginCtrl = (function() {
    LoginCtrl.$inject = ['$scope', 'Auth'];

    function LoginCtrl(scope, Auth) {
      this.scope = scope;
      this.Auth = Auth;
      this.submitting = false;
    }

    LoginCtrl.prototype.login = function(form) {
      var password, valid;
      if (this.submitting) {
        return;
      }
      this.scope.$broadcast('autofill:update');
      valid = form.$valid;
      if (!valid) {
        return;
      }
      this.submitting = true;
      password = md5(this.password);
      this.password = 'dont do it';
      return this.Auth.login(this.email, password, (function(_this) {
        return function() {
          return _this.submitting = false;
        };
      })(this));
    };

    return LoginCtrl;

  })());

}).call(this);
