// Generated by CoffeeScript 1.7.1
(function() {
  var SignUpCtrl;

  angular.module('BookStore').controller('SignUpCtrl', SignUpCtrl = (function() {
    SignUpCtrl.$inject = ['$scope', 'Auth', 'User'];

    function SignUpCtrl(scope, Auth, User) {
      this.scope = scope;
      this.Auth = Auth;
      this.User = User;
    }

    SignUpCtrl.prototype.submit = function(form) {
      var password, user;
      this.scope.$broadcast('autofill:update');
      if (!form.$valid) {
        return;
      }
      password = md5(this.password);
      user = new this.User({
        email: this.email,
        password: password,
        displayName: this.displayName
      });
      return user.$register().then(function(resp) {
        return this.Auth.login(this.email, password);
      })["catch"]((function(_this) {
        return function(resp) {
          var errs;
          errs = resp.data;
          _this.errors = {};
          return angular.forEach(errs, function(err, field) {
            form[field].$setValidity('mongoose', false);
            return _this.errors[field] = err.type;
          });
        };
      })(this));
    };

    return SignUpCtrl;

  })());

}).call(this);
