// Generated by CoffeeScript 1.7.1
(function() {
  var Auth;

  angular.module('BookStore').service('Auth', Auth = (function() {
    Auth.$inject = ['$location', '$rootScope', '$cookieStore', '$http'];

    function Auth($location, $rootScope, $cookieStore, $http) {
      $rootScope.user = $cookieStore.get('user') || {};
      this.login = function(email, password, callback) {
        if (callback == null) {
          callback = angular.noop;
        }
        return $http.post("" + window.api_host + "/api/login?hashed=true", {
          email: email,
          password: password
        }).then(function(resp) {
          var user;
          user = angular.extend(resp.data, {
            password: password
          });
          $rootScope.user = user;
          $cookieStore.put('user', user);
          callback(null, $rootScope.user);
          return $location.path('/books');
        }, function(err) {
          $cookieStore.remove('user');
          return callback(err);
        });
      };
      this.logout = function(callback) {
        if (callback == null) {
          callback = angular.noop;
        }
        return $http.post("" + window.api_host + "/api/logout").then(function() {
          $rootScope.user = {};
          $cookieStore.remove('user');
          $location.path('/');
          return callback();
        });
      };
      this.isLoggedIn = function() {
        var _ref;
        return !!((_ref = $rootScope.user) != null ? _ref.email : void 0);
      };
    }

    return Auth;

  })());

}).call(this);
