// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('BookStore').factory('Book', function($resource, $q, $location) {
    return $resource("" + window.api_host + "/api/books/:id", {
      id: '@id'
    }, {
      update: {
        method: 'PUT',
        params: {}
      },
      get: {
        method: 'GET',
        interceptor: {
          responseError: function(resp) {
            if (resp.status === 404) {
              $location.path('/error/404');
            }
            return $q.reject(resp);
          }
        }
      }
    });
  });

}).call(this);
