// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('BookStore').factory('User', function($resource) {
    return $resource("" + window.api_host + "/api/users/:id", {
      id: '@id'
    }, {
      update: {
        method: 'PUT',
        params: {}
      },
      get: {
        method: 'GET',
        params: {
          id: 'me'
        }
      },
      register: {
        method: 'POST',
        params: {
          hashed: 'true'
        }
      }
    });
  });

}).call(this);
