// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('BookStore').directive('autofillEnabled', function() {
    return {
      require: 'ngModel',
      link: function(scope, elem, attr, ngModel) {
        return scope.$on('autofill:update', function() {
          return ngModel.$setViewValue(elem.val());
        });
      }
    };
  });

}).call(this);
