// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('BookStore').directive('inputMatch', function($parse) {
    return {
      require: '?ngModel',
      restrict: 'A',
      link: function(scope, elem, attr, ngModel) {
        var firstPasswordGetter, validator;
        if (!ngModel) {
          return;
        }
        firstPasswordGetter = $parse(attr['inputMatch']);
        validator = function(value) {
          var password;
          password = firstPasswordGetter(scope);
          ngModel.$setValidity('match', password === value);
          return value;
        };
        ngModel.$parsers.unshift(validator);
        ngModel.$formatters.push(validator);
        return attr.$observe('inputMatch', function() {
          return validator(ngModel.$viewValue);
        });
      }
    };
  });

}).call(this);
